application: test-webpy03
version: 1
api_version: 1
runtime: python

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /slideimg
  static_dir: slideimg
- url: /static
  static_dir: static
- url: .*
  script: hello.py
